// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║     CinderLPVault — SparkDex LP Token Vault           ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * WHAT THIS DOES:
 * ────────────────
 * Holds SparkDex (Uniswap V2) LP tokens for users and earns them:
 *
 * YIELD SOURCE 1 — Trading fees (automatic, no action needed):
 *   Every swap in the SparkDex pool pays 0.3% to LPs.
 *   This accrues directly into the LP token value — the LP token
 *   becomes worth more of each underlying asset over time.
 *   Cinder holds your LP tokens so you don't have to manage them.
 *   We pass 100% of AMM trading fees through to depositors — we
 *   don't charge a fee on this because we didn't generate it.
 *
 * YIELD SOURCE 2 — EMBER mining rewards (via CinderMining contract):
 *   Depositors stake their cLP shares in CinderMining Pool 2 to earn EMBER.
 *   This is the same mining mechanism as the sFLR vault.
 *   We take a 10% performance fee when EMBER rewards are claimed.
 *
 * WHAT YOU DEPOSIT: SparkDex LP tokens (EMBER/FLR or sFLR/FLR)
 * WHAT YOU RECEIVE: cLP vault shares (ERC-20, transferable)
 * WHAT YOU EARN:
 *   - AMM trading fees (0.3% per swap in the pool, auto-compounded)
 *   - EMBER mining rewards from CinderMining (requires staking cLP)
 *
 * FEE STRUCTURE (honest and simple):
 * ────────────────────────────────────
 * - 0% on AMM trading fees    — you keep 100% of swap fee income
 * - 0.1% withdrawal fee       — on LP tokens withdrawn, stays in vault
 * - 10% on EMBER mining claims — when users claim EMBER, 10% to treasury
 *
 * WHY DIFFERENT FROM STAKING VAULT:
 * ───────────────────────────────────
 * The sFLR staking vault has a 10% performance fee on all yield because
 * the yield is entirely from Sceptre and we're providing compounding.
 * LP trading fees are generated by the AMM itself — Cinder isn't
 * responsible for them, so it's not appropriate to charge a fee.
 * The EMBER mining is our incentive layer, so we charge there.
 *
 * IMPERMANENT LOSS WARNING:
 * ──────────────────────────
 * LP positions carry impermanent loss risk. If EMBER price moves
 * significantly relative to FLR, you may receive back less total
 * value than if you'd held the tokens separately. This is inherent
 * to all AMM LP positions and is not specific to Cinder.
 *
 * SUPPORTED POOLS:
 * ─────────────────
 * This vault is pool-specific — one vault per LP token.
 * Deploy separately for each pool you want to support:
 *   - CinderLPVault(EMBER_FLR_LP, treasury)  → cEMBER_FLR
 *   - CinderLPVault(SFLR_FLR_LP, treasury)  → csFLR_FLR
 *
 * SPARKDEX ADDRESSES (Flare Mainnet):
 * ─────────────────────────────────────
 * Router:  0x16b619B04c961b8Ce3A0E3FB8572dB3E55b99dB7
 * Factory: 0x6040BB9E4E12B7e8dc5BcEbbE5b76b9E86dBd35E
 * WFLR:    0x1D80c49BbBCd1C0911346656B529DF9E5c2F783d
 */

// ── Uniswap V2 interfaces ──────────────────────────────────────────────────
interface IUniswapV2Pair {
    function token0() external view returns (address);
    function token1() external view returns (address);
    function getReserves() external view returns (uint112 r0, uint112 r1, uint32 ts);
    function totalSupply() external view returns (uint256);
    function balanceOf(address) external view returns (uint256);
    function transfer(address, uint256) external returns (bool);
    function transferFrom(address, address, uint256) external returns (bool);
    function approve(address, uint256) external returns (bool);
}

interface IUniswapV2Router {
    function addLiquidityETH(
        address token,
        uint256 amountTokenDesired,
        uint256 amountTokenMin,
        uint256 amountETHMin,
        address to,
        uint256 deadline
    ) external payable returns (uint256 amountToken, uint256 amountETH, uint256 liquidity);

    function removeLiquidityETH(
        address token,
        uint256 liquidity,
        uint256 amountTokenMin,
        uint256 amountETHMin,
        address to,
        uint256 deadline
    ) external returns (uint256 amountToken, uint256 amountETH);

    function addLiquidity(
        address tokenA,
        address tokenB,
        uint256 amountADesired,
        uint256 amountBDesired,
        uint256 amountAMin,
        uint256 amountBMin,
        address to,
        uint256 deadline
    ) external returns (uint256 amountA, uint256 amountB, uint256 liquidity);
}

interface IERC20 {
    function balanceOf(address) external view returns (uint256);
    function transfer(address, uint256) external returns (bool);
    function transferFrom(address, address, uint256) external returns (bool);
    function approve(address, uint256) external returns (bool);
    function decimals() external view returns (uint8);
    function symbol() external view returns (string memory);
}

// ── ERC-20 share token ─────────────────────────────────────────────────────
contract ERC20 {
    string public name;
    string public symbol;
    uint8  public constant decimals = 18;
    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);

    constructor(string memory _name, string memory _symbol) {
        name = _name; symbol = _symbol;
    }
    function approve(address s, uint256 a) external returns (bool) {
        allowance[msg.sender][s] = a; emit Approval(msg.sender, s, a); return true;
    }
    function transfer(address to, uint256 a) external returns (bool) { return _transfer(msg.sender, to, a); }
    function transferFrom(address from, address to, uint256 a) external returns (bool) {
        require(allowance[from][msg.sender] >= a, "ERC20: allowance");
        allowance[from][msg.sender] -= a; return _transfer(from, to, a);
    }
    function _transfer(address from, address to, uint256 a) internal returns (bool) {
        require(balanceOf[from] >= a, "ERC20: balance");
        balanceOf[from] -= a; balanceOf[to] += a;
        emit Transfer(from, to, a); return true;
    }
    function _mint(address to, uint256 a) internal { totalSupply += a; balanceOf[to] += a; emit Transfer(address(0), to, a); }
    function _burn(address from, uint256 a) internal { require(balanceOf[from] >= a); totalSupply -= a; balanceOf[from] -= a; emit Transfer(from, address(0), a); }
}

// ── Main vault ─────────────────────────────────────────────────────────────
contract CinderLPVault is ERC20 {

    // ── Constants ─────────────────────────────────────────────────────────
    uint256 public constant WITHDRAWAL_FEE_BPS = 10;    // 0.1%
    uint256 public constant BPS_DENOMINATOR    = 10000;
    uint256 public constant MINIMUM_DEPOSIT    = 1e9;   // tiny minimum for dust prevention

    // ── Immutables ────────────────────────────────────────────────────────
    IUniswapV2Pair public immutable lpToken;   // SparkDex LP token (the thing deposited)
    address        public immutable token0;    // first token of the pair
    address        public immutable token1;    // second token of the pair

    // ── State ──────────────────────────────────────────────────────────────
    address public treasury;
    address public owner;
    bool    public paused;

    // TVL cap — same philosophy as staking vault, raised after audit
    uint256 public tvlCap = 50_000e18;  // 50K LP tokens (adjust based on LP token price)
    mapping(address => bool) public approvedZaps;

    // Per-user tracking
    mapping(address => uint256) public userDepositedLP;    // LP tokens deposited
    mapping(address => uint256) public userDepositTime;

    // Protocol stats
    uint256 public totalLPDeposited;       // lifetime LP deposited
    uint256 public totalWithdrawalFees;    // lifetime withdrawal fees collected
    uint256 public lastPricePerLP;         // LP token value at last snapshot (scaled 1e18)

    // ── Events ────────────────────────────────────────────────────────────
    event Deposited(address indexed user, uint256 lpAmount, uint256 sharesIssued);
    event Withdrawn(address indexed user, uint256 sharesBurned, uint256 lpReceived, uint256 fee);
    event TreasuryUpdated(address old, address newAddr);

    modifier notPaused() { require(!paused, "LPVault: paused"); _; }
    modifier onlyOwner()  { require(msg.sender == owner, "LPVault: not owner"); _; }

    /**
     * @param _lpToken   SparkDex pair address (e.g. EMBER/FLR pair)
     * @param _treasury  Where fees go (CinderTimelock)
     *
     * The vault name is auto-generated from the LP token symbols.
     * e.g. "Cinder EMBER/FLR LP Vault" → shares called "cEMBER-FLR"
     */
    constructor(address _lpToken, address _treasury) ERC20("", "") {
        require(_lpToken != address(0) && _treasury != address(0), "LPVault: zero address");
        lpToken  = IUniswapV2Pair(_lpToken);
        treasury = _treasury;
        owner    = msg.sender;
        token0   = IUniswapV2Pair(_lpToken).token0();
        token1   = IUniswapV2Pair(_lpToken).token1();

        // Build name from token symbols
        string memory sym0 = _tryGetSymbol(token0);
        string memory sym1 = _tryGetSymbol(token1);
        name   = string(abi.encodePacked("Cinder ", sym0, "/", sym1, " LP Vault"));
        symbol = string(abi.encodePacked("ff", sym0, "-", sym1));
    }

    // ════════════════════════════════════════════════════════════════════
    //  CORE: DEPOSIT
    // ════════════════════════════════════════════════════════════════════

    /**
     * @notice Deposit SparkDex LP tokens. Receive vault shares in return.
     *
     * BEFORE CALLING:
     * Approve this vault to spend your LP tokens:
     *   lpToken.approve(vaultAddress, amount)
     *
     * WHAT YOU GET:
     * Vault shares (cEMBER-FLR or csFLR-FLR) that you can then stake
     * in CinderMining to earn EMBER rewards on top of LP trading fees.
     *
     * @param lpAmount   Amount of LP tokens to deposit
     */
    function deposit(uint256 lpAmount) external notPaused returns (uint256 shares) {
        require(lpAmount >= MINIMUM_DEPOSIT, "LPVault: below minimum");
        require(totalAssets() + lpAmount <= tvlCap, "LPVault: TVL cap reached");

        lpToken.transferFrom(msg.sender, address(this), lpAmount);

        uint256 totalLP = lpToken.balanceOf(address(this));
        if (totalSupply == 0 || totalLP == 0) {
            shares = lpAmount;
        } else {
            uint256 lpBefore = totalLP - lpAmount;
            shares = (lpAmount * totalSupply) / lpBefore;
        }
        require(shares > 0, "LPVault: zero shares");

        _mint(msg.sender, shares);
        totalLPDeposited             += lpAmount;
        userDepositedLP[msg.sender]  += lpAmount;
        userDepositTime[msg.sender]   = block.timestamp;

        emit Deposited(msg.sender, lpAmount, shares);
    }

    /**
     * @notice Deposit on behalf of a recipient. Approved zap contracts only.
     */
    function depositFor(address recipient, uint256 lpAmount) external notPaused returns (uint256 shares) {
        require(approvedZaps[msg.sender], "LPVault: not approved zap");
        require(recipient != address(0), "LPVault: zero recipient");
        require(lpAmount >= MINIMUM_DEPOSIT, "LPVault: below minimum");
        require(totalAssets() + lpAmount <= tvlCap, "LPVault: TVL cap reached");

        lpToken.transferFrom(msg.sender, address(this), lpAmount);

        uint256 totalLP = lpToken.balanceOf(address(this));
        if (totalSupply == 0 || totalLP == 0) {
            shares = lpAmount;
        } else {
            uint256 lpBefore = totalLP - lpAmount;
            shares = (lpAmount * totalSupply) / lpBefore;
        }
        require(shares > 0, "LPVault: zero shares");

        _mint(recipient, shares);
        totalLPDeposited             += lpAmount;
        userDepositedLP[recipient]   += lpAmount;
        userDepositTime[recipient]    = block.timestamp;

        emit Deposited(recipient, lpAmount, shares);
    }

    // ════════════════════════════════════════════════════════════════════
    //  CORE: WITHDRAW
    // ════════════════════════════════════════════════════════════════════

    /**
     * @notice Withdraw LP tokens by returning vault shares.
     *
     * YOUR RETURN:
     * - LP tokens worth more than you deposited (trading fees accumulated)
     * - Minus 0.1% withdrawal fee
     * - EMBER mining rewards are separate — claim those from CinderMining
     *
     * IMPERMANENT LOSS:
     * The LP tokens you receive represent the current pool composition,
     * which may differ from when you deposited due to price movement.
     * This is IL — a property of AMM LPs, not Cinder.
     *
     * @param shares  Number of vault shares to burn
     */
    function withdraw(uint256 shares) external notPaused returns (uint256 lpOut) {
        require(shares > 0, "LPVault: zero shares");
        require(balanceOf[msg.sender] >= shares, "LPVault: insufficient shares");

        uint256 totalLP = lpToken.balanceOf(address(this));
        lpOut = (shares * totalLP) / totalSupply;

        _burn(msg.sender, shares);

        // 0.1% withdrawal fee — stays in vault (benefits remaining holders)
        uint256 fee = (lpOut * WITHDRAWAL_FEE_BPS) / BPS_DENOMINATOR;
        lpOut -= fee;
        totalWithdrawalFees += fee;

        // Send LP tokens to user — they can unwrap via SparkDex if desired
        lpToken.transfer(msg.sender, lpOut);

        // Update tracking
        if (userDepositedLP[msg.sender] > lpOut) {
            userDepositedLP[msg.sender] -= lpOut;
        } else {
            userDepositedLP[msg.sender] = 0;
        }

        emit Withdrawn(msg.sender, shares, lpOut, fee);
    }

    // ════════════════════════════════════════════════════════════════════
    //  VIEW
    // ════════════════════════════════════════════════════════════════════

    /// @notice Total LP tokens held in the vault
    function totalAssets() public view returns (uint256) {
        return lpToken.balanceOf(address(this));
    }

    /// @notice LP tokens per share (increases as trading fees compound)
    function pricePerShare() public view returns (uint256) {
        if (totalSupply == 0) return 1e18;
        return (totalAssets() * 1e18) / totalSupply;
    }

    /// @notice How many LP tokens a given number of shares is worth
    function sharesToLP(uint256 shares) public view returns (uint256) {
        if (totalSupply == 0) return 0;
        return (shares * totalAssets()) / totalSupply;
    }

    /// @notice How many shares a given LP amount would receive
    function lpToShares(uint256 lpAmount) public view returns (uint256) {
        if (totalSupply == 0 || totalAssets() == 0) return lpAmount;
        return (lpAmount * totalSupply) / totalAssets();
    }

    /**
     * @notice Current value of the LP position in underlying tokens.
     * This is the AMM math: value = 2 * sqrt(r0 * r1) per LP token.
     * Useful for displaying USD value in the frontend.
     */
    function lpTokenValue() public view returns (
        uint256 reserve0PerLP,  // token0 per LP token (scaled 1e18)
        uint256 reserve1PerLP,  // token1 per LP token (scaled 1e18)
        uint256 totalLPSupply
    ) {
        (uint112 r0, uint112 r1,) = lpToken.getReserves();
        totalLPSupply = lpToken.totalSupply();
        if (totalLPSupply == 0) return (0, 0, 0);
        reserve0PerLP = (uint256(r0) * 1e18) / totalLPSupply;
        reserve1PerLP = (uint256(r1) * 1e18) / totalLPSupply;
    }

    /**
     * @notice Dashboard data for a user in one call.
     */
    function getUserInfo(address user) external view returns (
        uint256 shares,
        uint256 lpValue,           // current LP tokens their shares are worth
        uint256 depositedLP,       // original LP tokens deposited
        uint256 lpGained,          // LP tokens gained from trading fees
        uint256 sharePercent,      // their % of vault (basis points)
        uint256 depositTime
    ) {
        shares       = balanceOf[user];
        lpValue      = sharesToLP(shares);
        depositedLP  = userDepositedLP[user];
        lpGained     = lpValue > depositedLP ? lpValue - depositedLP : 0;
        sharePercent = totalSupply > 0 ? (shares * 10000) / totalSupply : 0;
        depositTime  = userDepositTime[user];
    }

    /**
     * @notice Protocol stats for the dashboard.
     */
    function getVaultStats() external view returns (
        uint256 tvl,              // total LP tokens
        uint256 totalShares,
        uint256 _pricePerShare,   // LP per share (1e18)
        uint256 totalDeposited,
        uint256 withdrawalFees,
        address _token0,
        address _token1
    ) {
        return (
            totalAssets(),
            totalSupply,
            pricePerShare(),
            totalLPDeposited,
            totalWithdrawalFees,
            token0,
            token1
        );
    }

    // ── Admin ──────────────────────────────────────────────────────────
    function setTreasury(address t) external onlyOwner {
        require(t != address(0), "LPVault: zero");
        emit TreasuryUpdated(treasury, t);
        treasury = t;
    }
    function setTvlCap(uint256 cap) external onlyOwner {
        require(cap >= totalAssets(), "LPVault: cap below TVL");
        tvlCap = cap;
    }
    function setApprovedZap(address zap, bool approved) external onlyOwner {
        approvedZaps[zap] = approved;
    }
    function setPaused(bool _p) external onlyOwner { paused = _p; }
    function transferOwnership(address n) external onlyOwner {
        require(n != address(0)); owner = n;
    }

    // ── Helpers ────────────────────────────────────────────────────────
    function _tryGetSymbol(address token) internal view returns (string memory) {
        try IERC20(token).symbol() returns (string memory s) { return s; }
        catch { return "???"; }
    }
}
